import { NextPage } from "next";
import Head from 'next/head'
import { Cleanup } from "../../Cleanup";
import { CleanupDisplay } from "../components/CleanupDisplay";

const Feed: NextPage = () => {
  let cleanups: Array<Cleanup> = [];

  cleanups = [
    new Cleanup(
      'Lady Bird Lake Cleanup',
      'Come help out Austin',
      'First St Bridge. Austin, TX 78701',
      new Date(Date.now()),
      new Date(Date.now() + 2 * 60 * 60 * 1000), // 2 hours after now
      ['https://www.kxan.com/wp-content/uploads/sites/40/2022/08/Trash-building-up-in-Lady-Bird-Lake.png?w=1280']
    ),
    new Cleanup(
      'Galveston Beach',
      'Clear our beaches',
      '6285 Seawall Blvd, Galveston, TX 77551',
      new Date(Date.now() + 48 * 60 * 60 * 1000),
      new Date(Date.now() + 52 * 60 * 60 * 1000),
      ['https://media.12newsnow.com/assets/KJAC/images/5716aaab-ac60-408e-a4c4-003ddff39240/5716aaab-ac60-408e-a4c4-003ddff39240_750x422.jpg']
    )
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cleanups.map((cleanup, index) => <CleanupDisplay key={index} cleanup={cleanup} />)}
    </div>
  );
}

export default Feed;